Update submodule and patches
Submodule ffmpeg 9cb9da62a35..0dcbe1c1aa8
Modified 0005, 0028, 0057, 0067-0076, 0085, 0087, 0091, 0094, 0099

Signed-off-by: Haihao Xiang <haihao.xiang@intel.com>

diff --git a/patches/0076-configure-add-enable-libvpl-option.patch b/patches/0076-configure-add-enable-libvpl-option.patch
--- a/patches/0076-configure-add-enable-libvpl-option.patch
+++ b/patches/0076-configure-add-enable-libvpl-option.patch
@@ -1,7 +1,7 @@
-From 9c5cabf9803ac023acb6743688b65ee870a039a5 Mon Sep 17 00:00:00 2001
+From 2c3f1d498b6b5e114f71484279b179eaa729a385 Mon Sep 17 00:00:00 2001
 From: Haihao Xiang <haihao.xiang@intel.com>
 Date: Wed, 3 Feb 2021 14:49:46 +0800
-Subject: [PATCH 55/65] configure: add --enable-libvpl option
+Subject: [PATCH 55/70] configure: add --enable-libvpl option
 
 This allows user to build FFmpeg against Intel oneVPL. oneVPL 2.6
 is the required minimum version when building Intel oneVPL code.
@@ -26,14 +26,14 @@ $ ffmpeg -init_hw_device dxva2=d3d9:0 -init_hw_device qsv=qsv@d3d9 -hwaccel qsv 
 
 [1] https://www.intel.com/content/www/us/en/develop/documentation/upgrading-from-msdk-to-onevpl/top.html
 ---
- configure | 27 +++++++++++++++++++++------
- 1 file changed, 21 insertions(+), 6 deletions(-)
+ configure | 29 ++++++++++++++++++++++-------
+ 1 file changed, 22 insertions(+), 7 deletions(-)
 
 diff --git a/configure b/configure
-index ef2b7f7437..7006019955 100755
+index 4ca22272e3..3a5b69c274 100755
 --- a/configure
 +++ b/configure
-@@ -339,6 +339,7 @@ External library support:
+@@ -341,6 +341,7 @@ External library support:
    --disable-ffnvcodec      disable dynamically linked Nvidia code [autodetect]
    --enable-libdrm          enable DRM code (Linux) [no]
    --enable-libmfx          enable Intel MediaSDK (AKA Quick Sync Video) code via libmfx [no]
@@ -41,7 +41,7 @@ index ef2b7f7437..7006019955 100755
    --enable-libnpp          enable Nvidia Performance Primitives-based code [no]
    --enable-mmal            enable Broadcom Multi-Media Abstraction Layer (Raspberry Pi) via MMAL [no]
    --disable-nvdec          disable Nvidia video decoding acceleration (via hwaccel) [autodetect]
-@@ -1917,6 +1918,7 @@ HWACCEL_LIBRARY_NONFREE_LIST="
+@@ -1921,6 +1922,7 @@ HWACCEL_LIBRARY_NONFREE_LIST="
  HWACCEL_LIBRARY_LIST="
      $HWACCEL_LIBRARY_NONFREE_LIST
      libmfx
@@ -49,7 +49,7 @@ index ef2b7f7437..7006019955 100755
      mmal
      omx
      opencl
-@@ -6548,22 +6550,35 @@ enabled libilbc           && require libilbc ilbc.h WebRtcIlbcfix_InitDecode -li
+@@ -6559,23 +6561,36 @@ enabled libjxl            && require_pkg_config libjxl "libjxl >= 0.7.0" jxl/dec
  enabled libklvanc         && require libklvanc libklvanc/vanc.h klvanc_context_create -lklvanc
  enabled libkvazaar        && require_pkg_config libkvazaar "kvazaar >= 0.8.1" kvazaar.h kvz_api_get
  enabled liblensfun        && require_pkg_config liblensfun lensfun lensfun.h lf_db_new
@@ -62,20 +62,23 @@ index ef2b7f7437..7006019955 100755
  # Media SDK or Intel Media Server Studio, these don't come with
  # pkg-config support.  Instead, users should make sure that the build
  # can find the libraries and headers through other means.
--
--enabled libmfx            && { { check_pkg_config libmfx "libmfx < 2.0" "mfxvideo.h" MFXInit ||
+-enabled libmfx            && { { check_pkg_config libmfx "libmfx >= 1.28 libmfx < 2.0" "mfxvideo.h" MFXInit ||
 +elif enabled libmfx; then
-+    { check_pkg_config libmfx "libmfx < 2.0" "mfxvideo.h" MFXInit || \
++    { check_pkg_config libmfx "libmfx >= 1.28 libmfx < 2.0" "mfxvideo.h" MFXInit ||
  # Some old versions of libmfx have the following settings in libmfx.pc:
  #   includedir=/usr/include
  #   Cflags: -I${includedir}
  # So add -I${includedir}/mfx to CFLAGS
--                                 { check_pkg_config libmfx "libmfx < 2.0" "mfx/mfxvideo.h" MFXInit && add_cflags -I${libmfx_incdir}/mfx; } ||
--                                 { require "libmfx < 2.0" "mfxvideo.h" MFXInit "-llibmfx $advapi32_extralibs" && warn "using libmfx without pkg-config"; } } &&
+-                                 { check_pkg_config libmfx "libmfx >= 1.28 libmfx < 2.0" "mfx/mfxvideo.h" MFXInit && add_cflags -I${libmfx_incdir}/mfx; } ||
+-                                 { require libmfx "mfxvideo.h mfxdefs.h" MFXInit "-llibmfx $advapi32_extralibs" &&
+-                                   { test_cpp_condition mfxdefs.h "MFX_VERSION >= 1028 && MFX_VERSION < 2000" || die "ERROR: libmfx version must be >= 1.28 and < 2.0"; }  &&
+-                                     warn "using libmfx without pkg-config"; } } &&
 -                               warn "build FFmpeg against libmfx 1.x, obsolete features of libmfx such as OPAQUE memory,\n"\
 -                                    "multi-frame encode, user plugins and LA_EXT rate control mode are enabled"; }
-+      { check_pkg_config libmfx "libmfx < 2.0" "mfx/mfxvideo.h" MFXInit && add_cflags -I${libmfx_incdir}/mfx; } ||
-+      { require "libmfx < 2.0" "mfxvideo.h" MFXInit "-llibmfx $advapi32_extralibs" && warn "using libmfx without pkg-config"; } } &&
++      { check_pkg_config libmfx "libmfx >= 1.28 libmfx < 2.0" "mfx/mfxvideo.h" MFXInit && add_cflags -I${libmfx_incdir}/mfx; } ||
++      { require libmfx "mfxvideo.h mfxdefs.h" MFXInit "-llibmfx $advapi32_extralibs" &&
++        { test_cpp_condition mfxdefs.h "MFX_VERSION >= 1028 && MFX_VERSION < 2000" || die "ERROR: libmfx version must be >= 1.28 and < 2.0"; }  &&
++        warn "using libmfx without pkg-config"; } } &&
 +    warn "build FFmpeg against libmfx 1.x, obsolete features of libmfx such as OPAQUE memory,\n"\
 +         "multi-frame encode, user plugins and LA_EXT rate control mode are enabled"
 +elif enabled libvpl; then
@@ -87,10 +90,9 @@ index ef2b7f7437..7006019955 100755
 +             "and LA_EXT rate control mode in FFmpeg QSV won't be supported." ||
 +            die "ERROR: libvpl >= 2.6 not found"
 +fi
-+
+ 
  if enabled libmfx; then
     check_cc MFX_CODEC_VP9 "mfxdefs.h mfxstructures.h" "MFX_CODEC_VP9"
- fi
 -- 
 2.17.1
 
